/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface StringReverserInterface extends Interface {
  getFunction(
    nameOrSignature: "reverseAscii" | "reverseString"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "reverseAscii",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "reverseString",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "reverseAscii",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reverseString",
    data: BytesLike
  ): Result;
}

export interface StringReverser extends BaseContract {
  connect(runner?: ContractRunner | null): StringReverser;
  waitForDeployment(): Promise<this>;

  interface: StringReverserInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  reverseAscii: TypedContractMethod<[s: string], [string], "view">;

  reverseString: TypedContractMethod<[s: string], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "reverseAscii"
  ): TypedContractMethod<[s: string], [string], "view">;
  getFunction(
    nameOrSignature: "reverseString"
  ): TypedContractMethod<[s: string], [string], "view">;

  filters: {};
}
